name: Spark Build and Test

on:
  push:
    branches:
      - main  # Adjust this to your main branch name or desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java, Scala, and Spark
        uses: olafurpg/setup-scala@v11
        with:
          scala-version: 2.12.14
          sbt-version: 1.5.5

      - name: Build and Test Spark Application
        run: sbt clean test

      - name: Determine Semantic Version
        id: semver
        run: |
          echo "SEMVER=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t talk2toks/spark-word-count:${{ env.SEMVER }} .
          docker tag talk2toks/spark-word-count:${{ env.SEMVER }}

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u talk2toks --password-stdin
          docker push talk2toks/your-spark-app:${{ env.SEMVER }}