name: Spark Build and Test
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java, Scala, and Spark
        uses: olafurpg/setup-scala@v11
        with:
          scala-version: 2.12.14
          sbt-version: 1.5.5

      - name: Build and Test Spark Application
        run: sbt clean test

      - name: Build JAR
        run: sbt assembly

      - name: Determine Semantic Version
        id: semver
        run: |
          echo "SEMVER=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          #push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          #push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spark-word-count:v0.1.0
          labels: ${{ steps.metadata.outputs.labels }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_AUTH_CONFIG: '{"auths": {"https://index.docker.io/v1/": {"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}", "email": "igeadetokunbo@gmail.com"}}}'

      - name: Look up images
        run: docker image ls
      
      # push the image manually, see above comment
      - name: Docker Build image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/spark-word-count:v0.1.0
      
      # push the image manually, see above comment
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spark-word-count:v0.1.0

