name: Spark Build and Test

on:
  push:
    branches:
      - main  # Adjust this to your main branch name or desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java, Scala, and Spark
        uses: olafurpg/setup-scala@v11
        with:
          scala-version: 2.12.14
          sbt-version: 1.5.5

      - name: Build and Test Spark Application
        run: sbt clean test